In [1]:
import json
import time
from datetime import datetime, timezone
from dateutil import parser as dtparser

import requests
import pandas as pd

In [2]:
GAMMA_BASE = "https://gamma-api.polymarket.com"  # market + event metadata
# (Later you may also use data feeds / websockets, but start with Gamma for ingestion)

In [3]:
session = requests.Session()
session.headers.update({"User-Agent": "bit-polymarket-signal-scanner/0.1"})

def get_json(url, params=None, timeout=30, max_retries=3, backoff=1.5):
    last_err = None
    for attempt in range(max_retries):
        try:
            r = session.get(url, params=params, timeout=timeout)
            r.raise_for_status()
            return r.json()
        except Exception as e:
            last_err = e
            sleep_s = backoff ** attempt
            print(f"[warn] GET failed ({attempt+1}/{max_retries}) -> {e}. Sleeping {sleep_s:.1f}s")
            time.sleep(sleep_s)
    raise last_err

In [4]:
slug = "what-price-will-bitcoin-hit-in-february-2026"  # example slug used in docs
url = f"{GAMMA_BASE}/events"
data = get_json(url, params={"slug": slug})

type(data), (len(data) if isinstance(data, list) else data.keys())

(list, 1)

In [5]:
print(json.dumps(data[0], indent=2)[:10000])  # print first ~4k chars

{
  "id": "194107",
  "ticker": "what-price-will-bitcoin-hit-in-february-2026",
  "slug": "what-price-will-bitcoin-hit-in-february-2026",
  "title": "What price will Bitcoin hit in February?",
  "description": "What price will Bitcoin hit in February?",
  "resolutionSource": "",
  "startDate": "2026-01-31T02:17:18.974124Z",
  "creationDate": "2026-01-31T02:17:18.974091Z",
  "endDate": "2026-03-01T05:00:00Z",
  "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
  "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
  "active": true,
  "closed": false,
  "archived": false,
  "new": false,
  "featured": true,
  "restricted": true,
  "liquidity": 4910007.19172,
  "volume": 83546757.012751,
  "openInterest": 0,
  "createdAt": "2026-01-31T02:13:32.238365Z",
  "updatedAt": "2026-02-20T08:39:32.897369Z",
  "competitive": 0.9148921570869833,
  "volume24hr": 4945522.189421,
  "volume1wk": 39319057.140504,
  "volume1mo": 83522161.95170498,
  "volume1yr": 83522161.95170498,
  "enableOrderBook": true,
  "liquidityClob": 4910007.19172,
  "negRisk": false,
  "commentCount": 0,
  "markets": [
    {
      "id": "1303355",
      "question": "Will Bitcoin reach $150,000 in February?",
      "conditionId": "0x5e5c9dfaf695371a0cc321b47b35f66a6dbd1482f0503526603d2bd2a91bfdc7",
      "slug": "will-bitcoin-reach-150k-in-february-2026",
      "endDate": "2026-03-01T05:00:00Z",
      "liquidity": "1744348.2429",
      "startDate": "2026-01-31T02:16:17.311269Z",
      "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
      "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
      "description": "This market will immediately resolve to \"Yes\" if any Binance 1 minute candle for BTC/USDT during the month specified in the title (from 00:00 AM ET on the first day to 11:59 PM ET on the last), has a final High price equal to or greater than the price specified in the title. Otherwise, this market will resolve to \"No.\"\n\nThe resolution source for this market is Binance, specifically the BTC/USDT High prices available at https://www.binance.com/en/trade/BTC_USDT, with the chart settings on \"1m\" for one-minute candles selected on the top bar.\n\nPlease note that the outcome of this market depends solely on the price data from the Binance BTC/USDT trading pair. Prices from other exchanges, different trading pairs, or spot markets will not be considered for the resolution of this market.",
      "outcomes": "[\"Yes\", \"No\"]",
      "outcomePrices": "[\"0.0015\", \"0.9985\"]",
      "volume": "20958246.903516",
      "active": true,
      "closed": false,
      "marketMakerAddress": "",
      "createdAt": "2026-01-31T02:13:34.065821Z",
      "updatedAt": "2026-02-20T08:42:52.760736Z",
      "new": false,
      "featured": false,
      "submitted_by": "0x91430CaD2d3975766499717fA0D66A78D814E5c5",
      "archived": false,
      "resolvedBy": "0x65070BE91477460D8A7AeEb94ef92fe056C2f2A7",
      "restricted": true,
      "groupItemTitle": "\u2191 150,000",
      "groupItemThreshold": "0",
      "questionID": "0x4bbc933474649343cfb8b96d5daef2db544dd54d1739230c7b33dd32cea33b8b",
      "enableOrderBook": true,
      "orderPriceMinTickSize": 0.001,
      "orderMinSize": 5,
      "volumeNum": 20958246.903516,
      "liquidityNum": 1744348.2429,
      "endDateIso": "2026-03-01",
      "startDateIso": "2026-01-31",
      "hasReviewedDates": true,
      "volume24hr": 1293520.4909999997,
      "volume1wk": 10181894.391283996,
      "volume1mo": 20956317.215515986,
      "volume1yr": 20956317.215515986,
      "clobTokenIds": "[\"37297213992198847758335843642137412014662841314020423585709724457305615671955\", \"85285091029101061598102453878417748165438482105623263900746828987387745601127\"]",
      "umaBond": "500",
      "umaReward": "2",
      "volume24hrClob": 1293520.4909999997,
      "volume1wkClob": 10181894.391283996,
      "volume1moClob": 20956317.215515986,
      "volume1yrClob": 20956317.215515986,
      "volumeClob": 20958246.903516,
      "liquidityClob": 1744348.2429,
      "customLiveness": 0,
      "acceptingOrders": true,
      "negRisk": false,
      "negRiskRequestID": "",
      "ready": false,
      "funded": false,
      "acceptingOrdersTimestamp": "2026-01-31T02:15:12Z",
      "cyom": false,
      "competitive": 0.8009597099244316,
      "pagerDutyNotificationEnabled": false,
      "approved": true,
      "rewardsMinSize": 20,
      "rewardsMaxSpread": 3.5,
      "spread": 0.001,
      "oneWeekPriceChange": -0.001,
      "lastTradePrice": 0.002,
      "bestBid": 0.001,
      "bestAsk": 0.002,
      "automaticallyActive": true,
      "clearBookOnStart": true,
      "manualActivation": false,
      "negRiskOther": false,
      "umaResolutionStatuses": "[]",
      "pendingDeployment": false,
      "deploying": false,
      "deployingTimestamp": "2026-01-31T02:13:49.187022Z",
      "rfqEnabled": false,
      "holdingRewardsEnabled": false,
      "feesEnabled": false,
      "requiresTranslation": false,
      "feeType": null
    },
    {
      "id": "1303361",
      "question": "Will Bitcoin reach $120,000 in February?",
      "conditionId": "0xee97e9edec0727d16dcfe4040dca1c949d45e4010de05569fb5a4e7a9873a83d",
      "slug": "will-bitcoin-reach-120k-in-february-2026",
      "endDate": "2026-03-01T05:00:00Z",
      "liquidity": "583039.26598",
      "startDate": "2026-01-31T02:16:19.8774Z",
      "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
      "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
      "description": "This market will immediately resolve to \"Yes\" if any Binance 1 minute candle for BTC/USDT during the month specified in the title (from 00:00 AM ET on the first day to 11:59 PM ET on the last), has a final High price equal to or greater than the price specified in the title. Otherwise, this market will resolve to \"No.\"\n\nThe resolution source for this market is Binance, specifically the BTC/USDT High prices available at https://www.binance.com/en/trade/BTC_USDT, with the chart settings on \"1m\" for one-minute candles selected on the top bar.\n\nPlease note that the outcome of this market depends solely on the price data from the Binance BTC/USDT trading pair. Prices from other exchanges, different trading pairs, or spot markets will not be considered for the resolution of this market.",
      "outcomes": "[\"Yes\", \"No\"]",
      "outcomePrices": "[\"0.0015\", \"0.9985\"]",
      "volume": "2850930.717175",
      "active": true,
      "closed": false,
      "marketMakerAddress": "",
      "createdAt": "2026-01-31T02:13:35.041462Z",
      "updatedAt": "2026-02-20T08:43:02.783614Z",
      "new": false,
      "featured": false,
      "submitted_by": "0x91430CaD2d3975766499717fA0D66A78D814E5c5",
      "archived": false,
      "resolvedBy": "0x65070BE91477460D8A7AeEb94ef92fe056C2f2A7",
      "restricted": true,
      "groupItemTitle": "\u2191 120,000",
      "groupItemThreshold": "2",
      "questionID": "0xc595d57aa2bcc54168a51556059f00f3a3616c17a2d785ce2601a38c62f059c0",
      "enableOrderBook": true,
      "orderPriceMinTickSize": 0.001,
      "orderMinSize": 5,
      "volumeNum": 2850930.717175,
      "liquidityNum": 583039.26598,
      "endDateIso": "2026-03-01",
      "startDateIso": "2026-01-31",
      "hasReviewedDates": true,
      "volume24hr": 675716.819941,
      "volume1wk": 1519666.5059470008,
      "volume1mo": 2849577.194174999,
      "volume1yr": 2849577.194174999,
      "clobTokenIds": "[\"101634930257850341602969673615351678146180846411766214423237977523476147979287\", \"54686656666443885986573295372690758310199066081424255164816980635327619857547\"]",
      "umaBond": "500",
      "umaReward": "2",
      "volume24hrClob": 675716.819941,
      "volume1wkClob": 1519666.5059470008,
      "volume1moClob": 2849577.194174999,
      "volume1yrClob": 2849577.194174999,
      "volumeClob": 2850930.717175,
      "liquidityClob": 583039.26598,
      "customLiveness": 0,
      "acceptingOrders": true,
      "negRisk": false,
      "negRiskRequestID": "",
      "ready": false,
      "funded": false,
      "acceptingOrdersTimestamp": "2026-01-31T02:15:14Z",
      "cyom": false,
      "competitive": 0.8009597099244316,
      "pagerDutyNotificationEnabled": false,
      "approved": true,
      "rewardsMinSize": 20,
      "rewardsMaxSpread": 3.5,
      "spread": 0.001,
      "oneWeekPriceChange": -0.001,
      "lastTradePrice": 0.002,
      "bestBid": 0.001,
      "bestAsk": 0.002,
      "automaticallyActive": true,
      "clearBookOnStart": true,
      "manualActivation": false,
      "negRiskOther": false,
      "umaResolutionStatuses": "[]",
      "pendingDeployment": false,
      "deploying": false,
      "deployingTimestamp": "2026-01-31T02:13:49.205138Z",
      "rfqEnabled": false,
      "holdingRewardsEnabled": false,
      "feesEnabled": false,
      "requiresTranslation": false,
      "feeType": null
    },
    {
      "id": "1303358",
      "question": "Will Bitcoin reach $125,000 in February?",
      "conditionId": "0x32a238c48ede8bc6386efceae61286deeb8528aec51d312e01082cf962280b4e",
      "slug": "will-bitcoin-reach-125k-in-february-2026",
      "endDate": "2026-03-01T05:00:00Z",
      "liquidity": "215877.75233",
      "startDate": "2026-01-31T02:16:26.077943Z",
      "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
      "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
      "description": "This market will immediately resolve to \"Yes\" if any Binance 1 minute candle for BTC/USDT during the month specified in the title (from 00:00 AM ET on the first day to 11:59 PM ET on the last), has a final High price equal to or greater than the price specified in the title. Otherwise, this market will resolve to \"No.\"\n\nThe resolution source for this market is Binance,

In [6]:
# The "Search Markets" doc page corresponds to Gamma's public search endpoint.
# We'll call it on gamma-api with a /search route.

query = "tariff"
search_url = f"{GAMMA_BASE}/public-search"
res = get_json(search_url, params={
    "q": query,
    "events_status": "active",  # try "active" first
    "limit_per_type": 20,
    "page": 1,
    "search_tags": True,
    "search_profiles": False,
})

print(res.keys())
print("markets:", len(res.get("markets", [])))
print("events:", [event["title"] for event in res.get("events", [])])
print("tags:", res.get("tags", []))

dict_keys(['events', 'tags', 'pagination'])
markets: 0
events: ['Will Trump create a tariff dividend by March 31?', 'Tariff increase on Canada in effect by June 30?', '100% tariff on Canada in effect by June 30?', 'Will Trump create a tariff dividend by June 30?', 'US tariff revenue up in Q4 2025?', 'What will Trump say in February?', "Supreme Court rules in favor of Trump's tariffs?", 'Will the Court Force Trump to Refund Tariffs?', "Will the Supreme Court rule on Trump's tariffs by...?", 'Will tariffs generate >$250b in 2025?', "How many SCOTUS justices rule in favor of Trump's tariffs?", 'How much revenue will the U.S. raise from tariffs in 2025?', 'Which countries will Trump make new trade deals with before 2027?']
tags: [{'id': '102012', 'label': 'Liberation Day Tariffs', 'slug': 'liberation-day-tariffs', 'event_count': 1}, {'id': '101758', 'label': 'Tariffs', 'slug': 'tariffs', 'event_count': 1}]

In [7]:
def brief_market(m):
    return {
        "id": m.get("id"),
        "slug": m.get("slug"),
        "title": m.get("title") or m.get("question"),
        "closed": m.get("closed"),
        "endDate": m.get("endDate"),
        "volume": m.get("volume"),
        
    }

df = pd.DataFrame([brief_market(m) for m in res.get("markets", [])]).head(10)
df

Empty DataFrame
Columns: []
Index: []

In [8]:
events_url = f"{GAMMA_BASE}/events"

# Start minimal; if you get too much data, add pagination/filters.
events = get_json(events_url, params={"status": "active", "limit": 20})

# events is typically a list; inspect first item
print(type(events), len(events))
print(json.dumps(events[0], indent=2)[:3500])

<class 'list'> 20
{
  "id": "2890",
  "ticker": "nba-will-the-mavericks-beat-the-grizzlies-by-more-than-5pt5-points-in-their-december-4-matchup",
  "slug": "nba-will-the-mavericks-beat-the-grizzlies-by-more-than-5pt5-points-in-their-december-4-matchup",
  "title": "NBA: Will the Mavericks beat the Grizzlies by more than 5.5 points in their December 4 matchup?",
  "description": "In the upcoming NBA game, scheduled for December 4:\n\nIf the Dallas Mavericks win by over 5.5 points, the market will resolve to \u201cYes\u201d.\n\nIf the Memphis Grizzlies lose by less than 5.5 points or win, the market will resolve \u201cNo.\u201d \n\nIf the game is not completed by December 11, 2021, the market will resolve 50-50.",
  "resolutionSource": "https://www.nba.com/games",
  "startDate": "2021-12-04T00:00:00Z",
  "creationDate": "2021-12-04T00:00:00Z",
  "endDate": "2021-12-04T00:00:00Z",
  "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/nba-will-the-mavericks-beat-the-grizzlies-by-more-than-55-points-in-their-december-4-matchup-543e7263-67da-4905-8732-cd3f220ae751.png",
  "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/nba-will-the-mavericks-beat-the-grizzlies-by-more-than-55-points-in-their-december-4-matchup-543e7263-67da-4905-8732-cd3f220ae751.png",
  "active": true,
  "closed": true,
  "archived": false,
  "new": false,
  "featured": false,
  "restricted": false,
  "liquidity": 0,
  "volume": 1335.05,
  "openInterest": 0,
  "sortBy": "ascending",
  "category": "Sports",
  "published_at": "2022-07-27 14:40:02.064+00",
  "createdAt": "2022-07-27T14:40:02.074Z",
  "updatedAt": "2024-04-25T18:49:06.075795Z",
  "competitive": 0,
  "volume24hr": 0,
  "volume1wk": 0,
  "volume1mo": 0,
  "volume1yr": 0,
  "liquidityAmm": 0,
  "liquidityClob": 0,
  "commentCount": 8125,
  "markets": [
    {
      "id": "239826",
      "question": "NBA: Will the Mavericks beat the Grizzlies by more than 5.5 points in their December 4 matchup?",
      "conditionId": "0x064d33e3f5703792aafa92bfb0ee10e08f461b1b34c02c1f02671892ede1609a",
      "slug": "nba-will-the-mavericks-beat-the-grizzlies-by-more-than-5pt5-points-in-their-december-4-matchup",
      "resolutionSource": "https://www.nba.com/games",
      "endDate": "2021-12-04T00:00:00Z",
      "category": "Sports",
      "liquidity": "50.000009",
      "startDate": "2021-12-04T19:35:03.796Z",
      "fee": "20000000000000000",
      "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/nba-will-the-mavericks-beat-the-grizzlies-by-more-than-55-points-in-their-december-4-matchup-aa2992d1-38df-404a-9190-49a909775014.png",
      "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/nba-will-the-mavericks-beat-the-grizzlies-by-more-than-55-points-in-their-december-4-matchup-aa2992d1-38df-404a-9190-49a909775014.png",
      "description": "In the upcoming NBA game, scheduled for December 4:\n\nIf the Dallas Mavericks win by over 5.5 points, the market will resolve to \u201cYes\u201d.\n\nIf the Memphis Grizzlies lose by less than 5.5 points or win, the market will resolve \u201cNo.\u201d \n\nIf the game is not completed by December 11, 2021, the market will resolve 50-50.",
      "outcomes": "[\"Yes\", \"No\"]",
      "outcomePrices": "[\"0.0000004113679809846114013590098187297978\", \"0.9999995886320190153885986409901813\"]",
      "volume": "1335.045385",
      "active": true,
      "marketType": "normal",
      "closed": true,
      "marketMakerAddress": "0x9c568Ce9a316e7CF9bCCA352b409dfDdCD9b2C08

In [9]:
markets_url = f"{GAMMA_BASE}/markets"

# pick 1 event
event_id = events[0].get("id")
event_slug = events[0].get("slug")
print("event_id:", event_id, "event_slug:", event_slug)

markets_for_event = get_json(markets_url, params={"event_id": event_id})
print("markets_for_event:", len(markets_for_event))
pd.DataFrame([brief_market(m) for m in markets_for_event]).head(10)

event_id: 2890 event_slug: nba-will-the-mavericks-beat-the-grizzlies-by-more-than-5pt5-points-in-their-december-4-matchup
markets_for_event: 20

,id,slug,title,closed,endDate,volume
0,12,will-joe-biden-get-coronavirus-before-the-elec...,Will Joe Biden get Coronavirus before the elec...,True,2020-11-04T00:00:00Z,32257.445115
1,17,will-airbnb-begin-publicly-trading-before-jan-...,Will Airbnb begin publicly trading before Jan ...,True,2021-01-02T00:00:00Z,89665.252158
2,18,will-a-new-supreme-court-justice-be-confirmed-...,Will a new Supreme Court Justice be confirmed ...,True,2020-11-04T00:00:00Z,43279.456005
3,19,will-kim-kardashian-and-kanye-west-divorce-bef...,Will Kim Kardashian and Kanye West divorce bef...,True,2021-01-02T00:00:00Z,22067.475119
4,20,will-coinbase-begin-publicly-trading-before-ja...,Will Coinbase begin publicly trading before Ja...,True,2021-01-02T00:00:00Z,116803.377183
5,36,what-will-the-price-of-bitcoin-be-on-november-...,What will the price of Bitcoin be on November ...,True,2020-11-04T00:00:00Z,59755.804763
6,40,will-trump-win-the-2020-us-presidential-election,Will Trump win the 2020 U.S. presidential elec...,True,2020-11-20T00:00:00Z,10802601.987023
7,42,will-there-be-an-emergency-use-authorization-g...,Will there be an Emergency Use Authorization (...,True,2020-11-04T00:00:00Z,21881.05833
8,43,what-will-the-total-value-locked-tvl-in-defi-b...,What will the total value locked (TVL) in DeFi...,True,2021-01-02T00:00:00Z,46944.579746
9,44,what-will-the-usd-price-of-filecoin-fil-be-on-...,What will the USD price of Filecoin ($FIL) be ...,True,2020-11-17T00:00:00Z,69947.098531

In [10]:
import os
from dotenv import load_dotenv
load_dotenv(".env", override=True)

from polyscanner.llm_gemini import generate_json

print("Has GOOGLE_API_KEY?", bool(os.getenv("GOOGLE_API_KEY")))
print("Model:", os.getenv("GEMINI_MODEL"))

out = generate_json(
    prompt='{"ping":"hello","instructions":"Return ONLY a JSON object with key ok=true"}',
    system="Return only JSON.",
    temperature=0.0,
)
out

ModuleNotFoundError: No module named 'polyscanner.llm_gemini'

In [11]:
from polyscanner.pipeline.minimal import run_minimal_pipeline

result = run_minimal_pipeline(top_n=10)  # uses DATABASE_URL + GOOGLE_API_KEY from .env
result["report_path"], result["llm_result"]
result["report_md"] #contains the full markdown text


import pandas as pd

items = result["llm_result"]["items"]
df = pd.DataFrame(items)

# optional: join market text back in (from ranked_markets)
markets = pd.DataFrame(result["ranked_markets"])[["pm_market_id", "question", "probability", "volume", "score"]]
df = df.merge(markets, on="pm_market_id", how="left")

df

/Users/nicolashoubouyan/Projects/BIT_case_study/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1183.35it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

GeminiError: Gemini JSON response was not an object

In [12]:
# Cell 1 — setup
import os, time, json
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import requests
from sentence_transformers import SentenceTransformer

BASE = os.getenv("POLYMARKET_API_BASE_URL") or "https://gamma-api.polymarket.com"
SESSION = requests.Session()
SESSION.headers.update({"User-Agent": "BIT-CaseStudy/0.1"})

model = SentenceTransformer("all-MiniLM-L6-v2", device="mps")  # or "cpu"

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2334.01it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [13]:
import psycopg, os
conn = psycopg.connect(os.getenv("DATABASE_URL"))
with conn.cursor() as cur:
    cur.execute("select now(), current_database(), version();")
    print(cur.fetchone())
conn.close()

(datetime.datetime(2026, 2, 20, 8, 46, 32, 329551, tzinfo=datetime.timezone.utc), 'postgres', 'PostgreSQL 17.6 on aarch64-unknown-linux-gnu, compiled by gcc (GCC) 15.2.0, 64-bit')

In [14]:
import os
from google import genai

# REPLACE with your actual key for this one test
client = genai.Client(api_key="AIzaSyB07wZkm06SnvFeNorLYAmZw6ct2vYpt5k")

try:
    response = client.models.generate_content(
        model="gemini-2.0-flash", 
        contents="hi"
    )
    print("Success! Quota is active.")
except Exception as e:
    print(f"Error details: {e}")

Error details: 400 INVALID_ARGUMENT. {'error': {'code': 400, 'message': 'API key expired. Please renew the API key.', 'status': 'INVALID_ARGUMENT', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'API_KEY_INVALID', 'domain': 'googleapis.com', 'metadata': {'service': 'generativelanguage.googleapis.com'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'API key expired. Please renew the API key.'}]}}

In [15]:
tags_r = requests.get("https://gamma-api.polymarket.com/tags", params={"limit":200})
tags_r.json()

[{'id': '671',
  'label': 'jto',
  'slug': 'jto',
  'publishedAt': '2023-12-07 19:16:45.979+00',
  'createdAt': '2023-12-07T19:16:45.993Z',
  'updatedAt': '2026-02-06T20:01:39.282804Z',
  'requiresTranslation': False},
 {'id': '101592',
  'label': 'Tom Aspinal',
  'slug': 'tom-aspinal',
  'createdAt': '2024-12-31T19:48:27.938591Z',
  'updatedAt': '2026-02-06T20:01:39.296759Z',
  'requiresTranslation': False},
 {'id': '101115',
  'label': 'Preston',
  'slug': 'preston',
  'createdAt': '2024-10-28T20:41:17.828152Z',
  'updatedAt': '2026-02-06T20:01:39.322562Z',
  'requiresTranslation': False},
 {'id': '746',
  'label': 'detroit pistons',
  'slug': 'detroit-pistons',
  'publishedAt': '2023-12-18 18:24:38.687+00',
  'createdAt': '2023-12-18T18:24:38.708Z',
  'updatedAt': '2026-02-06T20:01:39.323344Z',
  'requiresTranslation': False},
 {'id': '1493',
  'label': 'spider-man',
  'slug': 'spider-man',
  'publishedAt': '2024-02-27 19:31:50.152+00',
  'createdAt': '2024-02-27T19:31:50.171Z',
  'updatedAt': '2026-02-06T20:01:39.389634Z',
  'requiresTranslation': False},
 {'id': '1564',
  'label': 'facebook',
  'slug': 'facebook',
  'publishedAt': '2024-03-05 16:50:42.451+00',
  'createdAt': '2024-03-05T16:50:44.559Z',
  'updatedAt': '2026-02-06T20:01:39.417037Z',
  'requiresTranslation': False},
 {'id': '335',
  'label': 'peace deals',
  'slug': 'peace-deals',
  'publishedAt': '2023-11-02 21:56:32.239+00',
  'createdAt': '2023-11-02T21:56:32.251Z',
  'updatedAt': '2026-02-06T20:01:39.417937Z',
  'requiresTranslation': False},
 {'id': '103019',
  'label': 'Somali',
  'slug': 'somali',
  'createdAt': '2025-12-27T22:45:41.115947Z',
  'updatedAt': '2026-02-06T20:01:39.420361Z',
  'requiresTranslation': False},
 {'id': '103082',
  'label': 'Jungleman',
  'slug': 'jungleman',
  'createdAt': '2026-01-07T19:02:07.001529Z',
  'updatedAt': '2026-02-06T20:01:39.421154Z',
  'requiresTranslation': False},
 {'id': '680',
  'label': 'pudgy penguins',
  'slug': 'pudgy-penguins',
  'publishedAt': '2023-12-08 16:34:57.542+00',
  'createdAt': '2023-12-08T16:34:57.547Z',
  'updatedAt': '2026-02-06T20:01:39.42202Z',
  'requiresTranslation': False},
 {'id': '103061',
  'label': 'mag 7',
  'slug': 'mag-7',
  'createdAt': '2026-01-05T19:17:58.621353Z',
  'updatedAt': '2026-02-06T20:01:39.422725Z',
  'requiresTranslation': False},
 {'id': '100397',
  'label': 'fivethrityeight',
  'slug': 'fivethrityeight',
  'createdAt': '2024-08-28T22:05:20.893571Z',
  'updatedAt': '2026-02-06T20:01:39.423546Z',
  'requiresTranslation': False},
 {'id': '102787',
  'label': 'prop',
  'slug': 'prop',
  'createdAt': '2025-10-30T21:06:03.144996Z',
  'updatedAt': '2026-02-06T20:01:39.455764Z',
  'requiresTranslation': False},
 {'id': '311',
  'label': 'trade',
  'slug': 'trade',
  'publishedAt': '2023-11-02 21:53:18.067+00',
  'createdAt': '2023-11-02T21:53:18.166Z',
  'updatedAt': '2026-02-06T20:01:39.485138Z',
  'requiresTranslation': False},
 {'id': '100787',
  'label': 'CONMEBOL',
  'slug': 'conmebol',
  'createdAt': '2024-10-09T22:08:44.396352Z',
  'updatedAt': '2026-02-06T20:01:39.485792Z',
  'requiresTranslation': False},
 {'id': '101094',
  'label': 'Hawaii',
  'slug': 'hawaii',
  'createdAt': '2024-10-25T19:28:02.991592Z',
  'updatedAt': '2026-02-06T20:01:39.531179Z',
  'requiresTranslation': False},
 {'id': '100545',
  'label': 'slotkin',
  'slug': 'slotkin',
  'createdAt': '2024-09-19T21:57:29.844648Z',
  'updatedAt': '2026-02-06T20:01:39.556477Z',
  'requiresTranslation': False},
 {'id': '1510',
  'label': 'minnesota',
  'slug': 'minnesota',
  'publishedAt': '2024-02-28 22:12:58.233+00',
  'createdAt': '2024-02-28T22:13:00.833Z',
  'updatedAt': '2026-02-06T20:01:39.569996Z',
  'requiresTranslation': False},
 {'id': '100810',
  'label': 'Perfect Timing',
  'slug': 'perfect-timing',
  'createdAt': '2024-10-11T16:04:38.492954Z',
  'updatedAt': '2026-02-06T20:01:39.570616Z',
  'requiresTranslation': False},
 {'id': '100354',
  'label': 'Speed',
  'slug': 'speed',
  'createdAt': '2024-08-21T23:09:44.65522Z',
  'updatedAt': '2026-02-06T20:01:39.571401Z',
  'requiresTranslation': False},
 {'id': '103058',
  'label': 'Test1',
  'slug': 'test1',
  'forceShow': False,
  'createdAt': '2026-01-05T13:19:10.183265Z',
  'updatedAt': '2026-02-06T20:01:39.571942Z',
  'isCarousel': False,
  'requiresTranslation': False},
 {'id': '101414',
  'label': 'Checo Perez',
  'slug': 'checo-perez',
  'createdAt': '2024-12-03T18:01:36.597699Z',
  'updatedAt': '2026-02-06T20:02:41.693207Z',
  'requiresTranslation': False},
 {'id': '1619',
  'label': 'khalifa sall',
  'slug': 'khalifa-sall',
  'publishedAt': '2024-03-11 22:25:22.168+00',
  'createdAt': '2024-03-11T22:25:24.232Z',
  'updatedAt': '2026-02-06T20:02:41.694287Z',
  'requiresTranslation': False},
 {'id': '101451',
  'label': 'Joaquin Buckley',
  'slug': 'joaquin-buckley',
  'createdAt': '2024-12-09T23:02:30.506209Z',
  'updatedAt': '2026-02-06T20:02:41.695115Z',
  'requiresTranslation': False},
 {'id': '724',
  'label': 'charts',
  'slug': 'charts',
  'publishedAt': '2023-12-12 21:00:40.197+00',
  'createdAt': '2023-12-12T21:00:40.201Z',
  'updatedAt': '2026-02-06T20:02:41.695781Z',
  'requiresTranslation': False},
 {'id': '45',
  'label': 'trail blazers',
  'slug': 'trail-blazers',
  'publishedAt': '2023-11-02 21:13:49.657+00',
  'createdAt': '2023-11-02T21:13:49.664Z',
  'updatedAt': '2026-02-06T20:02:41.696437Z',
  'requiresTranslation': False},
 {'id': '101994',
  'label': 'NL Central',
  'slug': 'nl-central',
  'createdAt': '2025-03-25T22:33:44.61249Z',
  'updatedAt': '2026-02-06T20:02:41.697134Z',
  'requiresTranslation': False},
 {'id': '103174',
  'label': 'robert Fico',
  'slug': 'robert-fico',
  'createdAt': '2026-01-16T18:15:48.870744Z',
  'updatedAt': '2026-02-06T20:02:41.697973Z',
  'requiresTranslation': False},
 {'id': '100999',
  'label': 'Benfica',
  'slug': 'benfica',
  'createdAt': '2024-10-21T22:35:02.808325Z',
  'updatedAt': '2026-02-06T20:02:41.698673Z',
  'requiresTranslation': False},
 {'id': '101003',
  'label': 'Slovan Bratislava',
  'slug': 'slovan-bratislava',
  'createdAt': '2024-10-21T22:56:34.938223Z',
  'updatedAt': '2026-02-06T20:02:41.699411Z',
  'requiresTranslation': False},
 {'id': '1166',
  'label': 'the bear',
  'slug': 'the-bear',
  'publishedAt': '2024-02-06 19:53:22.312+00',
  'createdAt': '2024-02-06T19:53:22.341Z',
  'updatedAt': '2026-02-06T20:02:41.700051Z',
  'requiresTranslation': False},
 {'id': '100202',
  'label': 'DJTARCH',
  'slug': 'djt-1',
  'forceShow': False,
  'updatedAt': '2026-02-06T20:02:41.700828Z',
  'requiresTranslation': False},
 {'id': '1235',
  'label': 'psg',
  'slug': 'psg',
  'publishedAt': '2024-02-06 20:04:40.074+00',
  'createdAt': '2024-02-06T20:04:40.09Z',
  'updatedAt': '2026-02-06T20:02:41.701478Z',
  'requiresTranslation': False},
 {'id': '100370',
  'label': 'LLWS',
  'slug': 'llws',
  'createdAt': '2024-08-23T03:46:58.562337Z',
  'updatedAt': '2026-02-06T20:02:41.702265Z',
  'requiresTranslation': False},
 {'id': '75',
  'label': 'space exploration',
  'slug': 'space-exploration',
  'publishedAt': '2023-11-02 21:16:21.696+00',
  'createdAt': '2023-11-02T21:16:21.714Z',
  'updatedAt': '2026-02-06T20:02:41.702978Z',
  'requiresTranslation': False},
 {'id': '103106',
  'label': 'M&A',
  'slug': 'ma',
  'createdAt': '2026-01-09T23:07:35.624663Z',
  'updatedAt': '2026-02-06T20:02:41.703778Z',
  'requiresTranslation': False},
 {'id': '101073',
  'label': 'Syracuse',
  'slug': 'syracuse',
  'createdAt': '2024-10-24T17:40:48.732706Z',
  'updatedAt': '2026-02-06T20:02:41.704407Z',
  'requiresTranslation': False},
 {'id': '100231',
  'label': '100thieves',
  'slug': '100thieves',
  'createdAt': '2024-05-24T20:01:37.125466Z',
  'updatedAt': '2026-02-06T20:02:41.705177Z',
  'requiresTranslation': False},
 {'id': '101569',
  'label': 'Greenland',
  'slug': 'greenland',
  'createdAt': '2024-12-23T16:03:09.321825Z',
  'updatedAt': '2026-02-06T20:02:41.706139Z',
  'requiresTranslation': False},
 {'id': '665',
  'label': 'current events',
  'slug': 'current-events',
  'publishedAt': '2023-12-06 23:18:05.917+00',
  'createdAt': '2023-12-06T23:18:05.933Z',
  'updatedAt': '2026-02-06T20:02:41.706846Z',
  'requiresTranslation': False},
 {'id': '103114',
  'label': 'Super Rugby Pacific',
  'slug': 'super-rugby-pacific',
  'forceShow': False,
  'createdAt': '2026-01-10T19:23:06.213476Z',
  'updatedAt': '2026-02-06T20:02:41.707761Z',
  'isCarousel': False,
  'requiresTranslation': False},
 {'id': '103243',
  'label': 'adam 22',
  'slug': 'adam-22',
  'createdAt': '2026-01-23T16:01:01.747001Z',
  'updatedAt': '2026-02-06T20:02:41.708518Z',
  'requiresTranslation': False},
 {'id': '1225',
  'label': 'brian kelly',
  'slug': 'brian-kelly',
  'publishedAt': '2024-02-06 20:02:53.343+00',
  'createdAt': '2024-02-06T20:02:53.347Z',
  'updatedAt': '2026-02-06T20:02:41.709267Z',
  'requiresTranslation': False},
 {'id': '101646',
  'label': 'tax cut',
  'slug': 'tax-cut',
  'createdAt': '2025-01-07T01:10:40.126263Z',
  'updatedAt': '2026-02-06T20:02:41.710109Z',
  'requiresTranslation': False},
 {'id': '101771',
  'label': 'Myles Garrett',
  'slug': 'myles-garrett',
  'createdAt': '2025-02-03T16:30:03.706742Z',
  'updatedAt': '2026-02-06T20:02:41.711054Z',
  'requiresTranslation': False},
 {'id': '370',
  'label': 'GDP',
  'slug': 'gdp',
  'forceShow': False,
  'publishedAt': '2023-11-02 22:06:40.144+00',
  'createdAt': '2023-11-02T22:06:40.159Z',
  'updatedAt': '2026-02-06T20:02:41.711931Z',
  'isCarousel': False,
  'requiresTranslation': False},
 {'id': '101002',
  'label': 'Paris Saint-Germain',
  'slug': 'paris-saint-germain',
  'createdAt': '2024-10-21T22:54:19.309568Z',
  'updatedAt': '2026-02-06T20:02:41.712773Z',
  'requiresTranslation': False},
 {'id': '100629',
  'label': 'Mungo',
  'slug': 'mungo',
  'createdAt': '2024-09-23T19:37:45.64634Z',
  'updatedAt': '2026-02-06T20:02:41.713872Z',
  'requiresTranslation': False},
 {'id': '100135',
  'label': 'Toronto Maple Leafs',
  'slug': 'toronto-maple-leafs',
  'updatedAt': '2026-02-06T20:02:41.715139Z',
  'requiresTranslation': False},
 {'id': '101319',
  'label': 'Starmer',
  'slug': 'starmer',
  'createdAt': '2024-11-25T18:49:24.982919Z',
  'updatedAt': '2026-02-06T20:02:41.71586Z',
  'requiresTranslation': False},
 {'id': '100548',
  'label': 'amy klobuchar',
  'slug': 'amy-klobuchar',
  'createdAt': '2024-09-19T21:58:20.065203Z',
  'updatedAt': '2026-02-06T20:02:41.716877Z',
  'requiresTranslation': False},
 {'id': '100444',
  'label': 'fivethiryeight',
  'slug': 'fivethiryeight',
  'createdAt': '2024-09-11T22:05:58.30604Z',
  'updatedAt': '2026-02-06T20:02:41.717705Z',
  'requiresTranslation': False},
 {'id': '101706',
  'label': 'Ontario',
  'slug': 'ontario',
  'createdAt': '2025-01-16T20:44:09.711342Z',
  'updatedAt': '2026-02-06T20:02:41.718573Z',
  'requiresTranslation': False},
 {'id': '103030',
  'label': 'NYE',
  'slug': 'nye',
  'createdAt': '2025-12-29T16:44:50.487333Z',
  'updatedAt': '2026-02-06T20:02:41.719261Z',
  'requiresTranslation': False},
 {'id': '101758',
  'label': 'Tariffs',
  'slug': 'tariffs',
  'forceShow': False,
  'createdAt': '2025-02-02T18:39:54.837002Z',
  'updatedAt': '2026-02-06T20:02:41.720126Z',
  'requiresTranslation': False},
 {'id': '101536',
  'label': 'Alliance 90',
  'slug': 'alliance-90',
  'createdAt': '2024-12-17T22:18:51.725124Z',
  'updatedAt': '2026-02-06T20:02:41.720863Z',
  'requiresTranslation': False},
 {'id': '293',
  'label': 'doj',
  'slug': 'doj',
  'publishedAt': '2023-11-02 21:50:36.55+00',
  'createdAt': '2023-11-02T21:50:36.567Z',
  'updatedAt': '2026-02-06T20:02:41.72188Z',
  'requiresTranslation': False},
 {'id': '241',
  'label': 'SBF',
  'slug': 'sbf',
  'forceShow': False,
  'publishedAt': '2023-11-02 21:42:10.809+00',
  'createdAt': '2023-11-02T21:42:10.825Z',
  'updatedAt': '2026-02-06T20:02:41.722575Z',
  'requiresTranslation': False},
 {'id': '101856',
  'label': 'ASG',
  'slug': 'asg',
  'createdAt': '2025-02-13T20:16:16.012852Z',
  'updatedAt': '2026-02-06T20:02:41.723821Z',
  'requiresTranslation': False},
 {'id': '101417',
  'label': 'Bryce Hall',
  'slug': 'bryce-hall',
  'createdAt': '2024-12-03T22:12:15.000768Z',
  'updatedAt': '2026-02-06T20:02:41.724771Z',
  'requiresTranslation': False},
 {'id': '101074',
  'label': 'Assocaited Press',
  'slug': 'assocaited-press',
  'createdAt': '2024-10-24T17:57:23.549866Z',
  'updatedAt': '2026-02-06T20:02:41.725364Z',
  'requiresTranslation': False},
 {'id': '100384',
  'label': 'real clear',
  'slug': 'real-clear',
  'createdAt': '2024-08-27T19:35:39.28446Z',
  'updatedAt': '2026-02-06T20:02:41.726388Z',
  'requiresTranslation': False},
 {'id': '100320',
  'label': 'ME1',
  'slug': 'me1',
  'createdAt': '2024-07-26T23:58:26.151472Z',
  'updatedAt': '2026-02-06T20:02:41.72727Z',
  'requiresTranslation': False},
 {'id': '100813',
  'label': 'Jeanty',
  'slug': 'jeanty',
  'createdAt': '2024-10-11T16:10:17.399362Z',
  'updatedAt': '2026-02-06T20:02:41.728852Z',
  'requiresTranslation': False},
 {'id': '101072',
  'label': 'Cuse',
  'slug': 'cuse',
  'createdAt': '2024-10-24T17:40:48.46976Z',
  'updatedAt': '2026-02-06T20:02:41.729686Z',
  'requiresTranslation': False},
 {'id': '910',
  'label': 'zyn',
  'slug': 'zyn',
  'publishedAt': '2024-01-25 16:59:22.505+00',
  'createdAt': '2024-01-25T16:59:22.518Z',
  'updatedAt': '2026-02-06T20:02:41.730702Z',
  'requiresTranslation': False},
 {'id': '617',
  'label': 'token',
  'slug': 'token',
  'publishedAt': '2023-12-02 03:29:14.417+00',
  'createdAt': '2023-12-02T03:29:14.448Z',
  'updatedAt': '2026-02-06T20:02:41.731721Z',
  'requiresTranslation': False},
 {'id': '100328',
  'label': 'Economy',
  'slug': 'economy',
  'forceShow': False,
  'createdAt': '2024-08-05T05:34:54.235643Z',
  'updatedAt': '2026-02-06T20:02:41.732549Z',
  'requiresTranslation': False},
 {'id': '104',
  'label': 'giants',
  'slug': 'giants',
  'publishedAt': '2023-11-02 21:19:56.428+00',
  'createdAt': '2023-11-02T21:19:56.436Z',
  'updatedAt': '2026-02-06T20:02:41.73362Z',
  'requiresTranslation': False},
 {'id': '103244',
  'label': 'Mag7',
  'slug': 'mag7',
  'createdAt': '2026-01-23T16:39:54.914957Z',
  'updatedAt': '2026-02-06T20:02:41.734539Z',
  'requiresTranslation': False},
 {'id': '1042',
  'label': 'killers of the flower moon',
  'slug': 'killers-of-the-flower-moon',
  'publishedAt': '2024-02-06 19:33:54.581+00',
  'createdAt': '2024-02-06T19:33:54.601Z',
  'updatedAt': '2026-02-06T20:02:41.735358Z',
  'requiresTranslation': False},
 {'id': '101481',
  'label': 'uap',
  'slug': 'uap',
  'createdAt': '2024-12-12T17:08:40.299314Z',
  'updatedAt': '2026-02-06T20:02:41.736154Z',
  'requiresTranslation': False},
 {'id': '100689',
  'label': 'rebels',
  'slug': 'rebels',
  'createdAt': '2024-10-04T15:37:46.243548Z',
  'updatedAt': '2026-02-06T20:02:41.736771Z',
  'requiresTranslation': False},
 {'id': '744',
  'label': 'cryptocurrency',
  'slug': 'cryptocurrency',
  'forceShow': False,
  'publishedAt': '2023-12-18 17:29:51.762+00',
  'updatedBy': 15,
  'createdAt': '2023-12-18T17:29:51.782Z',
  'updatedAt': '2026-02-06T20:02:41.737624Z',
  'forceHide': True,
  'requiresTranslation': False},
 {'id': '101001',
  'label': 'Young Boys',
  'slug': 'young-boys',
  'createdAt': '2024-10-21T22:36:45.939393Z',
  'updatedAt': '2026-02-06T20:02:41.738305Z',
  'requiresTranslation': False},
 {'id': '101532',
  'label': 'Mykhailo Mudryk',
  'slug': 'mykhailo-mudryk',
  'createdAt': '2024-12-17T19:45:30.762104Z',
  'updatedAt': '2026-02-06T20:02:41.739033Z',
  'requiresTranslation': False},
 {'id': '65',
  'label': 'league of legends',
  'slug': 'league-of-legends',
  'publishedAt': '2023-11-02 21:15:32.598+00',
  'createdAt': '2023-11-02T21:15:32.602Z',
  'updatedAt': '2026-02-06T20:02:41.739793Z',
  'requiresTranslation': False},
 {'id': '101240',
  'label': 'clover',
  'slug': 'clover',
  'createdAt': '2024-11-12T16:03:12.817258Z',
  'updatedAt': '2026-02-06T20:02:41.740543Z',
  'requiresTranslation': False},
 {'id': '103025',
  'label': 'European Union',
  'slug': 'European-Union',
  'forceShow': False,
  'createdAt': '2025-12-28T18:20:52.989385Z',
  'updatedAt': '2026-02-06T20:02:41.741155Z',
  'isCarousel': False,
  'requiresTranslation': False},
 {'id': '1558',
  'label': 'caucus',
  'slug': 'caucus',
  'publishedAt': '2024-03-02 00:26:05.407+00',
  'createdAt': '2024-03-02T00:26:05.416Z',
  'updatedAt': '2026-02-06T20:02:41.742037Z',
  'requiresTranslation': False},
 {'id': '101070',
  'label': 'tape',
  'slug': 'tape',
  'createdAt': '2024-10-24T14:43:17.484448Z',
  'updatedAt': '2026-02-06T20:02:41.742662Z',
  'requiresTranslation': False},
 {'id': '102825',
  'label': 'Defi App',
  'slug': 'defi-app',
  'createdAt': '2025-11-10T17:31:09.570366Z',
  'updatedAt': '2026-02-06T20:02:41.743547Z',
  'requiresTranslation': False},
 {'id': '101185',
  'label': 'Union St-Gilloise',
  'slug': 'union-st-gilloise',
  'createdAt': '2024-11-05T21:45:42.169254Z',
  'updatedAt': '2026-02-06T20:02:41.744495Z',
  'requiresTranslation': False},
 {'id': '103091',
  'label': 'Homeland Security',
  'slug': 'homeland-security',
  'createdAt': '2026-01-08T18:29:51.111431Z',
  'updatedAt': '2026-02-06T20:02:41.745318Z',
  'requiresTranslation': False},
 {'id': '686',
  'label': 'cryptozoo',
  'slug': 'cryptozoo',
  'publishedAt': '2023-12-08 22:04:19.05+00',
  'createdAt': '2023-12-08T22:04:19.071Z',
  'updatedAt': '2026-02-06T20:02:41.746103Z',
  'requiresTranslation': False},
 {'id': '100974',
  'label': 'libertarian',
  'slug': 'libertarian',
  'createdAt': '2024-10-21T20:01:58.156431Z',
  'updatedAt': '2026-02-06T20:02:41.746919Z',
  'requiresTranslation': False},
 {'id': '101000',
  'label': 'Feyenoord',
  'slug': 'feyenoord',
  'createdAt': '2024-10-21T22:35:03.130021Z',
  'updatedAt': '2026-02-06T20:02:41.747616Z',
  'requiresTranslation': False},
 {'id': '100148',
  'label': 'slerf',
  'slug': 'slerf',
  'updatedAt': '2026-02-06T20:05:42.007629Z',
  'requiresTranslation': False},
 {'id': '1256',
  'label': 'crypto: the game',
  'slug': 'crypto-the-game',
  'publishedAt': '2024-02-06 20:07:55.6+00',
  'createdAt': '2024-02-06T20:07:55.612Z',
  'updatedAt': '2026-02-06T20:05:42.009784Z',
  'requiresTranslation': False},
 {'id': '1267',
  'label': 'business growth',
  'slug': 'business-growth',
  'publishedAt': '2024-02-06 20:09:49.882+00',
  'createdAt': '2024-02-06T20:09:49.912Z',
  'updatedAt': '2026-02-06T20:05:42.010632Z',
  'requiresTranslation': False},
 {'id': '102875',
  'label': 'Extended',
  'slug': 'extended',
  'createdAt': '2025-11-18T23:32:56.707627Z',
  'updatedAt': '2026-02-06T20:05:42.011394Z',
  'requiresTranslation': False},
 {'id': '100572',
  'label': 'sherrod brown',
  'slug': 'sherrod-brown',
  'createdAt': '2024-09-19T22:09:20.249219Z',
  'updatedAt': '2026-02-06T20:05:42.013006Z',
  'requiresTranslation': False},
 {'id': '102853',
  'label': 'Infinex',
  'slug': 'infinex',
  'createdAt': '2025-11-17T00:55:42.221319Z',
  'updatedAt': '2026-02-06T20:05:42.01381Z',
  'requiresTranslation': False},
 {'id': '100245',
  'label': 'Britain',
  'slug': 'britain',
  'forceShow': False,
  'createdAt': '2024-05-31T22:13:59.367615Z',
  'updatedAt': '2026-02-06T20:05:42.014526Z',
  'requiresTranslation': False},
 {'id': '100959',
  'label': 'NFL Week 7',
  'slug': 'nfl-week-7',
  'createdAt': '2024-10-18T21:17:49.085701Z',
  'updatedAt': '2026-02-06T20:02:00.227191Z',
  'requiresTranslation': False},
 {'id': '1563',
  'label': 'outage',
  'slug': 'outage',
  'publishedAt': '2024-03-05 16:50:43.894+00',
  'createdAt': '2024-03-05T16:50:44.058Z',
  'updatedAt': '2026-02-06T20:02:00.322493Z',
  'requiresTranslation': False},
 {'id': '103166',
  'label': 'NEH',
  'slug': 'neh',
  'createdAt': '2026-01-16T01:57:15.202417Z',
  'updatedAt': '2026-02-06T20:02:00.35936Z',
  'requiresTranslation': False},
 {'id': '630',
  'label': 'investments',
  'slug': 'investments',

In [16]:
# Cell 1 — setup
import os, time, json
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import requests
from sentence_transformers import SentenceTransformer

BASE = os.getenv("POLYMARKET_API_BASE_URL") or "https://gamma-api.polymarket.com"
SESSION = requests.Session()
SESSION.headers.update({"User-Agent": "BIT-CaseStudy/0.1"})

model = SentenceTransformer("all-MiniLM-L6-v2", device="mps")  # or "cpu"

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2440.70it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [17]:
# Cell 2 — Gamma helpers + "markets for tag" (via /events?tag_id=...)
def get_json(path: str, params: Optional[dict] = None, timeout_s: int = 30) -> Any:
    """Helper to retrieve json from gamma API

    Args:
        path (str): gamma api path
        params (Optional[dict], optional): _description_. Defaults to None.
        timeout_s (int, optional): _description_. Defaults to 30.

    Returns:
        Any: _description_
    """
    url = f"{BASE.rstrip('/')}{path}"
    r = SESSION.get(url, params=params or {}, timeout=timeout_s)
    r.raise_for_status()
    return r.json()

def try_get_json(path: str, params: Optional[dict] = None, timeout_s: int = 30) -> Tuple[bool, Any]:
    try:
        return True, get_json(path, params=params, timeout_s=timeout_s)
    except requests.HTTPError as e:
        return False, {"error": str(e), "status_code": getattr(e.response, "status_code", None), "path": path, "params": params}

def fetch_event_detail(event_id: Any) -> Optional[dict]:
    ok, data = try_get_json(f"/events/{event_id}", params=None)
    return data if ok and isinstance(data, dict) else None

def extract_markets_from_event(ev: dict) -> List[dict]:
    mkts = ev.get("markets")
    if isinstance(mkts, list) and mkts:
        return [m for m in mkts if isinstance(m, dict)]
    # sometimes events list responses omit markets; try detail fetch
    detail = fetch_event_detail(ev.get("id"))
    if detail and isinstance(detail.get("markets"), list):
        return [m for m in detail["markets"] if isinstance(m, dict)]
    return []

def fetch_markets_for_tag(
    tag_id: int,
    *,
    max_events_pages: int = 5,
    events_page_size: int = 50,
    markets_cap: int = 25,
    sleep_s: float = 0.05,
) -> List[dict]:
    markets_by_id: Dict[int, dict] = {}

    for page in range(max_events_pages):
        params = {
            "tag_id": str(tag_id),
            "closed": "false",
            "limit": str(events_page_size),
            "offset": str(page * events_page_size),
            # harmless if ignored; helps on some deployments
            "include_markets": "true",
        }
        ok, data = try_get_json("/events", params=params)
        if not ok:
            raise RuntimeError(f"Failed /events for tag_id={tag_id}: {data}")

        if not isinstance(data, list) or len(data) == 0:
            break

        for ev in data:
            if not isinstance(ev, dict):
                continue
            for m in extract_markets_from_event(ev):
                mid = m.get("id")
                if mid is None:
                    continue
                try:
                    mid_i = int(mid)
                except Exception:
                    continue
                if mid_i not in markets_by_id and (m.get("question") or m.get("title")):
                    markets_by_id[mid_i] = m
                    if len(markets_by_id) >= markets_cap:
                        return list(markets_by_id.values())

        time.sleep(sleep_s)

    return list(markets_by_id.values())

def build_tag_profile_text(tag: dict, markets: List[dict], *, max_questions: int = 20) -> str:
    label = (tag.get("label") or "").strip()
    slug = (tag.get("slug") or "").strip()
    tid = str(tag.get("id") or "").strip()

    questions = []
    for m in markets:
        q = (m.get("question") or m.get("title") or "").strip()
        if q:
            questions.append(q)
        if len(questions) >= max_questions:
            break

    # Profile = tag identity + concrete examples (what the tag retrieves)
    lines = [
        f"Polymarket tag profile.",
        f"tag_id: {tid}",
        f"label: {label}",
        f"slug: {slug}",
        "example_markets:",
        *[f"- {q}" for q in questions],
    ]
    return "\n".join(lines)

In [18]:
# Cell 3 — build tag+markets embeddings + similarity to your domains/themes
# Provide your selected tags as list[dict] with keys: id,label,slug
# Example: selected_tags = df_allow[["id","label","slug"]].to_dict("records")

In [19]:

# --- usage ---
# 1) define themes/domains you want to compare against
themes = [
    "AI & Data. AI models, LLMs, OpenAI, data platforms, AI regulation, GPUs.",
    "Compute & Semiconductors. GPUs, chips, foundries, semiconductor equipment, export controls, TSMC, ASML.",
    "Cloud & Software Infrastructure. AWS, Azure, GCP, enterprise SaaS spend, datacenters, observability, security.",
    "Consumer Internet & Digital Media. Social platforms, ads, e-commerce, app stores, antitrust.",
    "Fintech & Market Infrastructure. Payments rails, exchanges, brokerages, trading infrastructure.",
    "Digital Assets & Blockchain Infrastructure. Bitcoin, Ethereum, stablecoins, crypto ETFs, exchanges, regulation.",
    "Discount rate / Fed / inflation / rates.",
    "Regulation / antitrust / SEC / DOJ / FTC.",
    "Tariffs / export controls / sanctions / geopolitics.",
]
theme_emb = model.encode(themes, normalize_embeddings=True)

In [20]:
# Cell 4 — optionally cap to top K tags for embedding (keeps it fast)
TOP_K = 10000  # adjust
df_emb = df.head(TOP_K).copy()
df_emb[["id","label","slug","n_hits","hits"]].head(20)

KeyError: "None of [Index(['id', 'label', 'slug', 'n_hits', 'hits'], dtype='str')] are in the [columns]"

In [ ]:
# Cell 5 — embed tag texts
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2", device="mps")  # or "cpu"

texts = (df_emb["label"].fillna("") + " (" + df_emb["slug"].fillna("") + ")").tolist()
emb = model.encode(texts, normalize_embeddings=True, batch_size=128, show_progress_bar=True)
emb.shape

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 644.08it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 3/3 [00:00<00:00, 21.33it/s]

(354, 384)

In [ ]:
# Cell 6 — rank tags by similarity to a small set of themes (domain+channels)
themes = [
    "AI & Data: AI models, data platforms, AI regulation, OpenAI, GPUs",
    "Compute & Semiconductors: chips, GPUs, export controls, TSMC, ASML",
    "Cloud & Software Infrastructure: AWS Azure GCP, SaaS, enterprise software",
    "Consumer Internet & Digital Media: social, ads, e-commerce, platforms",
    "Fintech & Market Infrastructure: payments, exchanges, trading infra",
    "Digital Assets & Blockchain Infrastructure: bitcoin ethereum crypto ETFs stablecoins",
    "Discount rate / Fed / rates / inflation",
    "Regulation / antitrust / SEC / DOJ / FTC",
    "Tariffs / export controls / sanctions / geopolitics",
    "Demand shock / consumer spend / recession",
    "Supply shock / shortages / supply chain",
    "Hinge Health"
]

theme_emb = model.encode(themes, normalize_embeddings=True)

SIM_THRESHOLD = 0.3  # try 0.3–0.5

top_per_theme = {}
for j, theme in enumerate(themes):
    sims = S[:, j]
    idx = np.where(sims >= SIM_THRESHOLD)[0]
    idx = idx[np.argsort(-sims[idx])]  # sort remaining by similarity desc

    top_per_theme[theme] = (
        df_emb.loc[idx, ["id", "label", "slug", "n_hits"]]
        .assign(sim=sims[idx])
        .reset_index(drop=True)
    )

# optional: see how many tags survive per theme
{k: len(v) for k, v in top_per_theme.items()}

{'AI & Data: AI models, data platforms, AI regulation, OpenAI, GPUs': 15,
 'Compute & Semiconductors: chips, GPUs, export controls, TSMC, ASML': 1,
 'Cloud & Software Infrastructure: AWS Azure GCP, SaaS, enterprise software': 1,
 'Consumer Internet & Digital Media: social, ads, e-commerce, platforms': 6,
 'Fintech & Market Infrastructure: payments, exchanges, trading infra': 23,
 'Digital Assets & Blockchain Infrastructure: bitcoin ethereum crypto ETFs stablecoins': 28,
 'Discount rate / Fed / rates / inflation': 28,
 'Regulation / antitrust / SEC / DOJ / FTC': 26,
 'Tariffs / export controls / sanctions / geopolitics': 21,
 'Demand shock / consumer spend / recession': 12,
 'Supply shock / shortages / supply chain': 4,
 'Hinge Health': 4}

In [ ]:
# import tdqm as notebook_tdqm
from sentence_transformers import SentenceTransformer
import torch
import time
import requests
from typing import List
import numpy as np

/Users/nicolashoubouyan/Projects/BIT_case_study/venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2", device="mps")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1636.74it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [22]:
from polyscanner.ingestion.tag_base import run_tag_selection, DEFAULT_THEMES

res = run_tag_selection(
    tag_source="relevant_events",
    min_seed_hits=1,
    seed_exclude={"rates"},
    max_tag_candidates=10000,
    min_markets_per_tag=5,
    similarity_threshold=0.1,
    top_k_per_theme=25,
    dedupe_to_best_theme=False,
)

res["similarity_stats"]
{k: len(v) for k, v in res["selected_by_theme"].items()}

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 1712.16it/s, Materializing param=pooler.dense.weight]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Batches: 100%|██████████| 11/11 [00:01<00:00,  5.61it/s]
Batches: 100%|██████████| 1/1 [00:00<00:00, 19.39it/s]

{'fomc_surprises': 25,
 'real_yields_long_rates': 25,
 'us_china_semis_export_controls': 25,
 'taiwan_geopolitical_risk': 25,
 'crypto_regime_changes': 25,
 'ai_regulation_big_tech_enforcement': 25,
 'datacenter_power_grid_constraints': 25,
 'antitrust_platforms_app_stores_ads': 25,
 'it_spending_cycle_enterprise_cloud_ai': 25,
 'healthcare_policy_reimbursement': 25,
 'consumer_credit_conditions_cycle': 25}

In [23]:
res["theme_keys"]

['fomc_surprises',
 'real_yields_long_rates',
 'us_china_semis_export_controls',
 'taiwan_geopolitical_risk',
 'crypto_regime_changes',
 'ai_regulation_big_tech_enforcement',
 'datacenter_power_grid_constraints',
 'antitrust_platforms_app_stores_ads',
 'it_spending_cycle_enterprise_cloud_ai',
 'healthcare_policy_reimbursement',
 'consumer_credit_conditions_cycle']

In [24]:
res["selected_by_theme"][res["theme_keys"][0]]

[{'tag_id': 101337,
  'label': 'Parlays',
  'slug': 'parlays',
  'n_hits': 3,
  'n_markets': 15,
  'sim': 0.40934500098228455},
 {'tag_id': 107,
  'label': 'Business',
  'slug': 'business',
  'n_hits': 3,
  'n_markets': 15,
  'sim': 0.3833310306072235},
 {'tag_id': 103176,
  'label': 'Global Rates',
  'slug': 'Global-Rates',
  'n_hits': 2,
  'n_markets': 15,
  'sim': 0.3792918026447296},
 {'tag_id': 101522,
  'label': 'Japan',
  'slug': 'japan',
  'n_hits': 1,
  'n_markets': 15,
  'sim': 0.3519602119922638},
 {'tag_id': 101800,
  'label': 'Economic Policy',
  'slug': 'economic-policy',
  'n_hits': 3,
  'n_markets': 15,
  'sim': 0.33858218789100647},
 {'tag_id': 100418,
  'label': 'Derivatives',
  'slug': 'derivatives',
  'n_hits': 2,
  'n_markets': 15,
  'sim': 0.3337690830230713},
 {'tag_id': 103360,
  'label': 'Interest Rate',
  'slug': 'interest-rate',
  'n_hits': 2,
  'n_markets': 7,
  'sim': 0.3309359848499298},
 {'tag_id': 120,
  'label': 'Finance',
  'slug': 'finance',
  'n_hits': 3,
  'n_markets': 15,
  'sim': 0.32314062118530273},
 {'tag_id': 21,
  'label': 'Crypto',
  'slug': 'crypto',
  'n_hits': 4,
  'n_markets': 15,
  'sim': 0.31873226165771484},
 {'tag_id': 101796,
  'label': 'balance',
  'slug': 'balance',
  'n_hits': 1,
  'n_markets': 8,
  'sim': 0.31480133533477783},
 {'tag_id': 103715,
  'label': 'Hide From China',
  'slug': 'hide-from-china',
  'n_hits': 4,
  'n_markets': 15,
  'sim': 0.3089998662471771},
 {'tag_id': 101565,
  'label': 'budget',
  'slug': 'budget',
  'n_hits': 1,
  'n_markets': 6,
  'sim': 0.30860111117362976},
 {'tag_id': 734,
  'label': 'uk',
  'slug': 'uk',
  'n_hits': 1,
  'n_markets': 15,
  'sim': 0.3069736063480377},
 {'tag_id': 114,
  'label': 'Syria',
  'slug': 'syria',
  'n_hits': 1,
  'n_markets': 15,
  'sim': 0.30454060435295105},
 {'tag_id': 101751,
  'label': 'deficit',
  'slug': 'deficit',
  'n_hits': 1,
  'n_markets': 6,
  'sim': 0.30432555079460144},
 {'tag_id': 1312,
  'label': 'Crypto Prices',
  'slug': 'crypto-prices',
  'n_hits': 2,
  'n_markets': 15,
  'sim': 0.30269843339920044},
 {'tag_id': 101701,
  'label': 'cpi',
  'slug': 'cpi',
  'n_hits': 2,
  'n_markets': 15,
  'sim': 0.30128973722457886},
 {'tag_id': 102028,
  'label': 'Treasuries',
  'slug': 'treasuries',
  'n_hits': 2,
  'n_markets': 15,
  'sim': 0.29866254329681396},
 {'tag_id': 175,
  'label': 'nomination',
  'slug': 'nomination',
  'n_hits': 2,
  'n_markets': 5,
  'sim': 0.2985081374645233},
 {'tag_id': 101542,
  'label': 'Gov Shutdown',
  'slug': 'gov-shutdown',
  'n_hits': 1,
  'n_markets': 15,
  'sim': 0.2973220646381378},
 {'tag_id': 101970,
  'label': 'World',
  'slug': 'world',
  'n_hits': 4,
  'n_markets': 15,
  'sim': 0.29157721996307373},
 {'tag_id': 102198,
  'label': 'South Africa',
  'slug': 'south-africa',
  'n_hits': 1,
  'n_markets': 15,
  'sim': 0.2915109694004059},
 {'tag_id': 100171,
  'label': 'Stablecoins',
  'slug': 'stablecoins',
  'n_hits': 3,
  'n_markets': 15,
  'sim': 0.29138368368148804},
 {'tag_id': 101473,
  'label': 'MicroStrategy',
  'slug': 'microstrategy',
  'n_hits': 3,
  'n_markets': 10,
  'sim': 0.28915610909461975},
 {'tag_id': 129,
  'label': 'federal reserve',
  'slug': 'federal-reserve',
  'n_hits': 2,
  'n_markets': 7,
  'sim': 0.2884783148765564}]

In [25]:
# Given: res = run_tag_selection(...)

import re
import pandas as pd

# Index helpers
profiles_by_id = {p.tag_id: p for p in res["profiles"]}          # TagProfile
selected_by_theme = res["selected_by_theme"]                     # dict[str, list[dict]]

def theme_table(theme: str, n: int = 25) -> pd.DataFrame:
    rows = selected_by_theme.get(theme, [])
    df = pd.DataFrame(rows)
    if df.empty:
        return df
    if "sim" in df.columns:
        df = df.sort_values("sim", ascending=False)
    cols = [c for c in ["tag_id", "label", "slug", "sim", "n_hits", "n_markets"] if c in df.columns]
    return df[cols].head(n).reset_index(drop=True)

def show_tag_profile(tag_id: int, max_lines: int = 40) -> None:
    p = profiles_by_id.get(int(tag_id))
    if not p:
        print(f"tag_id={tag_id} not found in profiles")
        return
    txt = p.profile_text.strip()
    lines = txt.splitlines()
    print("\n".join(lines[:max_lines]))
    if len(lines) > max_lines:
        print(f"... ({len(lines)-max_lines} more lines)")

def inspect_theme(theme: str, n: int = 15, show_profiles: int = 3) -> pd.DataFrame:
    df = theme_table(theme, n=n)
    print(f"\n=== {theme} ===")
    if df.empty:
        print("No selected tags.")
        return df
    display(df)
    for tag_id in df["tag_id"].head(show_profiles).tolist():
        print(f"\n--- tag_id={tag_id} profile preview ---")
        show_tag_profile(int(tag_id), max_lines=25)
    return df

In [27]:
# Inspect all themes quickly (tables only)
for theme in res["theme_keys"]:
    df = theme_table(theme)
    print(theme, "->", len(df))
    if not df.empty:
        display(df)

fomc_surprises -> 25

    tag_id            label             slug       sim  n_hits  n_markets
0   101337          Parlays          parlays  0.409345       3         15
1      107         Business         business  0.383331       3         15
2   103176     Global Rates     Global-Rates  0.379292       2         15
3   101522            Japan            japan  0.351960       1         15
4   101800  Economic Policy  economic-policy  0.338582       3         15
5   100418      Derivatives      derivatives  0.333769       2         15
6   103360    Interest Rate    interest-rate  0.330936       2          7
7      120          Finance          finance  0.323141       3         15
8       21           Crypto           crypto  0.318732       4         15
9   101796          balance          balance  0.314801       1          8
10  103715  Hide From China  hide-from-china  0.309000       4         15
11  101565           budget           budget  0.308601       1          6
12     734               uk               uk  0.306974       1         15
13     114            Syria            syria  0.304541       1         15
14  101751          deficit          deficit  0.304326       1          6
15    1312    Crypto Prices    crypto-prices  0.302698       2         15
16  101701              cpi              cpi  0.301290       2         15
17  102028       Treasuries       treasuries  0.298663       2         15
18     175       nomination       nomination  0.298508       2          5
19  101542     Gov Shutdown     gov-shutdown  0.297322       1         15
20  101970            World            world  0.291577       4         15
21  102198     South Africa     south-africa  0.291511       1         15
22  100171      Stablecoins      stablecoins  0.291384       3         15
23  101473    MicroStrategy    microstrategy  0.289156       3         10
24     129  federal reserve  federal-reserve  0.288478       2          7

real_yields_long_rates -> 25

    tag_id             label              slug       sim  n_hits  n_markets
0   102028        Treasuries        treasuries  0.359713       2         15
1      107          Business          business  0.316349       3         15
2   103176      Global Rates      Global-Rates  0.303129       2         15
3   100418       Derivatives       derivatives  0.301322       2         15
4   102609       Freddie Mac       freddie-mac  0.289660       2         15
5   101800   Economic Policy   economic-policy  0.274024       3         15
6      702         Inflation         inflation  0.266115       2         15
7   101337           Parlays           parlays  0.265463       3         15
8   101522             Japan             japan  0.262855       1         15
9   101701               cpi               cpi  0.259508       2         15
10  103263      exhange rate      exhange-rate  0.255396       1          6
11     734                uk                uk  0.253189       1         15
12  103230              IBGE              ibge  0.245863       1         10
13      53            Movies            movies  0.239993       2         15
14  100328           Economy           economy  0.239860       3         15
15    1476                eu                eu  0.235169       1         15
16    1312     Crypto Prices     crypto-prices  0.233749       2         15
17  100171       Stablecoins       stablecoins  0.231371       3         15
18  103229              IPCA              ipca  0.229317       1         10
19  103353        best month        best-month  0.228173       2         12
20  102198      South Africa      south-africa  0.226180       1         15
21     167         argentina         argentina  0.225885       1         15
22  101705             forex             forex  0.225348       1         15
23  102000  Macro Indicators  macro-indicators  0.224320       2         15
24     604            Stocks            stocks  0.223509       3         15

us_china_semis_export_controls -> 25

    tag_id            label             slug       sim  n_hits  n_markets
0      303            China            china  0.351098       4         15
1   101758          Tariffs          tariffs  0.318635       2         15
2   103715  Hide From China  hide-from-china  0.298737       4         15
3   101999         Big Tech         big-tech  0.297929       3         15
4   101337          Parlays          parlays  0.292645       3         15
5   101761        Trade War        trade-war  0.276382       4         15
6   101970            World            world  0.263215       4         15
7   101734         DeepSeek         deepseek  0.262609       1         15
8      530           TikTok           tiktok  0.259619       1         11
9   102908              KHL              khl  0.250048       2         15
10  100412             NYSE             nyse  0.248247       2         15
11  102682         Indicies         indicies  0.244935       2         15
12  102691     Acquisitions     acquisitions  0.241083       3         15
13  102109           GTA VI           gta-vi  0.238908       1         14
14  102950      Warner Bros      warner-bros  0.237068       1         15
15     285       sam altman       sam-altman  0.234610       2         15
16    1401             Tech             tech  0.232553       3         15
17     235          Bitcoin          bitcoin  0.231702       3         15
18  102464            GPT-5            gpt-5  0.231286       2         15
19     107         Business         business  0.230521       3         15
20     596          Culture      pop-culture  0.228670       2         15
21  103665      Daily-Close      daily-close  0.228545       2         15
22     439               AI               ai  0.225421       3         15
23  102133          Today 🚀            today  0.225035       2         14
24  100266             NVDA             nvda  0.223952       2         15

taiwan_geopolitical_risk -> 25

    tag_id              label               slug       sim  n_hits  n_markets
0      303              China              china  0.405059       4         15
1      867             taiwan             taiwan  0.376821       4         15
2   103715    Hide From China    hide-from-china  0.362712       4         15
3     1563             outage             outage  0.300068       1         14
4   101794     Foreign Policy     foreign-policy  0.291324       3         15
5      596            Culture        pop-culture  0.289491       2         15
6   101761          Trade War          trade-war  0.288797       4         15
7   102109             GTA VI             gta-vi  0.281558       1         14
8   102908                KHL                khl  0.277943       2         15
9   101970              World              world  0.276826       4         15
10     570          Pandemics          pandemics  0.275311       1         15
11  100265        Geopolitics        geopolitics  0.271879       4         15
12     530             TikTok             tiktok  0.271687       1         11
13     192               nato               nato  0.265334       1         12
14  102205                 Xi                 xi  0.263466       1         15
15      78               Iran               iran  0.259122       2         15
16     270              putin              putin  0.253388       1         15
17     180             Israel             israel  0.251433       2         15
18     154        Middle East        middle-east  0.251173       2         15
19  101522              Japan              japan  0.249323       1         15
20  103388  Thailand Election  thailand-election  0.248295       1         15
21  101758            Tariffs            tariffs  0.246158       2         15
22     166        South Korea        south-korea  0.245528       1         15
23  102437  Thailand-Cambodia  thailand-cambodia  0.244364       1         15
24  101255     United Nations     united-nations  0.242576       1         15

crypto_regime_changes -> 25

    tag_id             label              slug       sim  n_hits  n_markets
0   103176      Global Rates      Global-Rates  0.431227       2         15
1      107          Business          business  0.429948       3         15
2      235           Bitcoin           bitcoin  0.418858       3         15
3   101337           Parlays           parlays  0.412659       3         15
4      120           Finance           finance  0.390750       3         15
5   101473     MicroStrategy     microstrategy  0.386216       3         10
6   103360     Interest Rate     interest-rate  0.381242       2          7
7   102682          Indicies          indicies  0.379797       2         15
8   101796           balance           balance  0.363496       1          8
9   102889              CFTC              cftc  0.361206       2          9
10  102849           S&P 500            sp-500  0.358518       2         15
11  101588  2025 Predictions  2025-predictions  0.353453       3         15
12      21            Crypto            crypto  0.352798       4         15
13  101758           Tariffs           tariffs  0.350713       2         15
14  101751           deficit           deficit  0.348714       1          6
15    1560              DOGE              doge  0.347260       1         14
16  100412              NYSE              nyse  0.341866       2         15
17  100328           Economy           economy  0.341727       3         15
18  103777     Top Performer     top-performer  0.337402       1         10
19  100171       Stablecoins       stablecoins  0.336196       3         15
20  101565            budget            budget  0.336133       1          6
21  102785          Metamask          metamask  0.333113       1         10
22  101800   Economic Policy   economic-policy  0.330392       3         15
23  101705             forex             forex  0.330018       1         15
24    1312     Crypto Prices     crypto-prices  0.329604       2         15

ai_regulation_big_tech_enforcement -> 25

,tag_id,label,slug,sim,n_hits,n_markets
0,103648,Claude 5,claude-5,0.295432,2,15
1,102950,Warner Bros,warner-bros,0.278381,1,15
2,473,gpt,gpt,0.277296,2,15
3,101999,Big Tech,big-tech,0.262920,3,15
4,101866,xAI,xai,0.261461,2,15
5,102464,GPT-5,gpt-5,0.256672,2,15
6,102691,Acquisitions,acquisitions,0.248838,3,15
7,1563,outage,outage,0.236210,1,14
8,303,China,china,0.234726,4,15
9,1628,Courts,courts,0.234061,2,15
10,101779,buy,buy,0.233547,1,15
11,530,TikTok,tiktok,0.232922,1,11
12,663,google,google,0.231097,2,15
13,102800,Gemini 3,gemini-3,0.225466,2,15
14,100187,SCOTUS,scotus,0.222269,2,8
15,101337,Parlays,parlays,0.216672,3,15
16,21,Crypto,crypto,0.213595,4,15
17,100188,Supreme Court,supreme-court,0.211586,2,15
18,103104,tarriffs,tarriffs,0.210134,2,15
19,540,Grok,grok,0.209603,2,15
20,93,Prediction Markets,prediction-markets,0.206317,2,15
21,100199,Senate,senate-elections,0.202115,2,15
22,1401,Tech,tech,0.200210,3,15
23,100412,NYSE,nyse,0.199709,2,15
24,439,AI,ai,0.197548,3,15

datacenter_power_grid_constraints -> 25

,tag_id,label,slug,sim,n_hits,n_markets
0,84,Weather,weather,0.223343,1,15
1,1563,outage,outage,0.223230,1,14
2,101734,DeepSeek,deepseek,0.190130,1,15
3,103040,Daily Temperature,temperature,0.182368,1,15
4,101542,Gov Shutdown,gov-shutdown,0.182022,1,15
5,100780,counter strike 2,counter-strike-2,0.180316,1,15
6,101999,Big Tech,big-tech,0.174001,3,15
7,570,Pandemics,pandemics,0.171038,1,15
8,1,Sports,sports,0.171013,2,15
9,1325,Space,space,0.167388,2,15
10,103037,Climate & Science,climate-science,0.167210,1,15
11,100412,NYSE,nyse,0.166988,2,15
12,100088,Hockey,hockey,0.166563,2,15
13,100350,Soccer,soccer,0.166067,2,15
14,102964,NFP,nfp,0.162926,1,15
15,1097,Apple,apple,0.161583,2,15
16,728,Tesla,tesla,0.161447,2,15
17,993,jobs,jobs,0.159613,1,14
18,100199,Senate,senate-elections,0.158565,2,15
19,103775,Department of Homeland Security,department-of-homeland-security,0.157698,1,15
20,745,NBA,nba,0.157571,1,15
21,537,OpenAI,openai,0.157533,3,15
22,600,IPOs,ipos,0.157241,2,15
23,103091,Homeland Security,homeland-security,0.156776,1,15
24,100091,New York City,new-york-city,0.156628,2,15

antitrust_platforms_app_stores_ads -> 25

,tag_id,label,slug,sim,n_hits,n_markets
0,970,App Store,app-store,0.361358,2,15
1,102950,Warner Bros,warner-bros,0.324748,1,15
2,102691,Acquisitions,acquisitions,0.311644,3,15
3,101779,buy,buy,0.304268,1,15
4,101999,Big Tech,big-tech,0.299322,3,15
5,234,blackrock,blackrock,0.297002,1,5
6,101758,Tariffs,tariffs,0.296795,2,15
7,102908,KHL,khl,0.294194,2,15
8,100187,SCOTUS,scotus,0.294147,2,8
9,102909,DEHL,dehl,0.292598,1,7
10,530,TikTok,tiktok,0.284517,1,11
11,93,Prediction Markets,prediction-markets,0.278911,2,15
12,101672,Valorant,valorant,0.278614,1,15
13,102756,Rocket League,rocket-league,0.277566,1,15
14,102910,CEHL,cehl,0.264577,1,8
15,771,Prince Andrew,prince-andrew,0.262515,1,5
16,303,China,china,0.261468,4,15
17,101970,World,world,0.261035,4,15
18,21,Crypto,crypto,0.254282,4,15
19,102889,CFTC,cftc,0.251055,2,9
20,102785,Metamask,metamask,0.246674,1,10
21,120,Finance,finance,0.246012,3,15
22,103104,tarriffs,tarriffs,0.244548,2,15
23,1401,Tech,tech,0.242492,3,15
24,102109,GTA VI,gta-vi,0.241672,1,14

it_spending_cycle_enterprise_cloud_ai -> 25

    tag_id         label          slug       sim  n_hits  n_markets
0   101999      Big Tech      big-tech  0.314932       3         15
1   102691  Acquisitions  acquisitions  0.285229       3         15
2      473           gpt           gpt  0.279748       2         15
3   103648      Claude 5      claude-5  0.277311       2         15
4   102464         GPT-5         gpt-5  0.274495       2         15
5      303         China         china  0.271234       4         15
6      285    sam altman    sam-altman  0.268175       2         15
7      530        TikTok        tiktok  0.267305       1         11
8      540          Grok          grok  0.265054       2         15
9     1401          Tech          tech  0.257522       3         15
10  101796       balance       balance  0.256923       1          8
11  102161      Jony Ive      jony-ive  0.254631       2         10
12  102849       S&P 500        sp-500  0.252859       2         15
13  102682      Indicies      indicies  0.251492       2         15
14  102679          MSFT          msft  0.248793       2         15
15    1563        outage        outage  0.247811       1         14
16  101779           buy           buy  0.244380       1         15
17  101565        budget        budget  0.240178       1          6
18  102800      Gemini 3      gemini-3  0.239429       2         15
19     570     Pandemics     pandemics  0.238020       1         15
20     439            AI            ai  0.237797       3         15
21  102785      Metamask      metamask  0.233870       1         10
22  102876        USD.AI       usdptai  0.233367       1         10
23     235       Bitcoin       bitcoin  0.228137       3         15
24  101866           xAI           xai  0.226345       2         15

healthcare_policy_reimbursement -> 25

,tag_id,label,slug,sim,n_hits,n_markets
0,103357,Influenza,influenza,0.259515,1,6
1,101462,flu,flu,0.248591,1,6
2,101337,Parlays,parlays,0.208779,3,15
3,570,Pandemics,pandemics,0.186496,1,15
4,514,Congress,congress,0.169918,2,15
5,103360,Interest Rate,interest-rate,0.163692,2,7
6,101758,Tariffs,tariffs,0.157144,2,15
7,100245,Britain,britain,0.154496,1,7
8,101565,budget,budget,0.151481,1,6
9,101062,Rogan,rogan,0.150571,1,15
10,103176,Global Rates,Global-Rates,0.149422,2,15
11,103676,Unemployment Insurance,unemployment-insurance,0.148783,1,7
12,1013,Earnings,earnings,0.143951,2,15
13,100207,Taxes,taxes,0.138735,2,9
14,101800,Economic Policy,economic-policy,0.138471,3,15
15,1401,Tech,tech,0.135317,3,15
16,101542,Gov Shutdown,gov-shutdown,0.135117,1,15
17,102756,Rocket League,rocket-league,0.133443,1,15
18,545,employment,employment,0.132140,1,6
19,102679,MSFT,msft,0.127474,2,15
20,100418,Derivatives,derivatives,0.126399,2,15
21,101796,balance,balance,0.125008,1,8
22,103196,Finance Rewards 300,finance-rewards-300,0.123800,2,15
23,102161,Jony Ive,jony-ive,0.123654,2,10
24,103158,HIP3,hip3,0.123639,1,10

consumer_credit_conditions_cycle -> 25

,tag_id,label,slug,sim,n_hits,n_markets
0,102609,Freddie Mac,freddie-mac,0.355941,2,15
1,103176,Global Rates,Global-Rates,0.270421,2,15
2,101522,Japan,japan,0.269587,1,15
3,102950,Warner Bros,warner-bros,0.267435,1,15
4,103353,best month,best-month,0.265862,2,12
5,101473,MicroStrategy,microstrategy,0.265573,3,10
6,107,Business,business,0.260283,3,15
7,120,Finance,finance,0.256548,3,15
8,101337,Parlays,parlays,0.255321,3,15
9,1330,nvidia,nvidia,0.253305,2,15
10,100266,NVDA,nvda,0.252857,2,15
11,102289,Midterms,midterms,0.248241,1,15
12,970,App Store,app-store,0.246414,2,15
13,102696,NFLX,nflx,0.246302,1,15
14,101641,self driving,self-driving,0.240883,1,8
15,235,Bitcoin,bitcoin,0.240127,3,15
16,1,Sports,sports,0.238257,2,15
17,103677,DOL,dol,0.237712,1,7
18,596,Culture,pop-culture,0.237674,2,15
19,439,AI,ai,0.236440,3,15
20,100199,Senate,senate-elections,0.233177,2,15
21,100350,Soccer,soccer,0.231417,2,15
22,100780,counter strike 2,counter-strike-2,0.230759,1,15
23,514,Congress,congress,0.230749,2,15
24,103196,Finance Rewards 300,finance-rewards-300,0.230475,2,15

In [28]:
# Deep inspect one theme (table + top profiles)
inspect_theme(res["themes"][0], n=20, show_profiles=5)

=== Monetary policy surprises (FOMC). Keywords: fomc, fed, powell, rate hike, rate cut, interest rate, basis points. ===
No selected tags.

Empty DataFrame
Columns: []
Index: []

In [29]:
# Optional: find "almost selected" tags for a theme using the stored similarity stats
# (useful when a theme has 0 results and you want to see what's closest)
import numpy as np

themes = res["themes"]
theme_emb = res["theme_embeddings"]
tag_emb = res["tag_embeddings"]
S = tag_emb @ theme_emb.T

def top_similar_profiles(theme: str, n: int = 20) -> pd.DataFrame:
    j = themes.index(theme)
    sims = S[:, j]
    idx = np.argsort(-sims)[:n]
    rows = []
    for i in idx:
        p = res["profiles"][int(i)]
        rows.append({
            "tag_id": p.tag_id,
            "label": p.label,
            "slug": p.slug,
            "sim": float(sims[i]),
            "n_hits": p.n_hits,
            "n_markets": p.n_markets,
        })
    return pd.DataFrame(rows)

# Example:
display(top_similar_profiles("Cloud & Software Infrastructure. AWS, Azure, GCP, enterprise SaaS spend, datacenters, observability, security.", n=30))

ValueError: list.index(x): x not in list